# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ident.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bident.proto\x12\x05ident\"3\n\x0b\x41uthRequest\x12\x15\n\ridentificacao\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\x05\"+\n\tAuthReply\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\x12\r\n\x05vetor\x18\x02 \x03(\x0c\"W\n\rCreateRequest\x12\x15\n\ridentificacao\x18\x01 \x01(\t\x12\r\n\x05senha\x18\x02 \x01(\x05\x12\x11\n\tpermissao\x18\x03 \x01(\t\x12\r\n\x05vetor\x18\x04 \x03(\x0c\"\x1e\n\x0b\x43reateReply\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\"\x1e\n\rAccessRequest\x12\r\n\x05vetor\x18\x01 \x03(\x0c\" \n\x0b\x41\x63\x63\x65ssReply\x12\x11\n\tpermissao\x18\x01 \x01(\t\"\x10\n\x0eTerminoRequest\"\x1f\n\x0cTerminoReply\x12\x0f\n\x07retorno\x18\x01 \x01(\x05\x32\xeb\x01\n\x0bIdentidades\x12\x36\n\x0c\x61utenticacao\x12\x12.ident.AuthRequest\x1a\x10.ident.AuthReply\"\x00\x12\x35\n\x07\x63riacao\x12\x14.ident.CreateRequest\x1a\x12.ident.CreateReply\"\x00\x12\x34\n\x06\x61\x63\x65sso\x12\x14.ident.AccessRequest\x1a\x12.ident.AccessReply\"\x00\x12\x37\n\x07termino\x12\x15.ident.TerminoRequest\x1a\x13.ident.TerminoReply\"\x00\x42\x1a\n\x05identB\nIdentProtoP\x01\xa2\x02\x02\x43Pb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ident_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\005identB\nIdentProtoP\001\242\002\002CP'
  _AUTHREQUEST._serialized_start=22
  _AUTHREQUEST._serialized_end=73
  _AUTHREPLY._serialized_start=75
  _AUTHREPLY._serialized_end=118
  _CREATEREQUEST._serialized_start=120
  _CREATEREQUEST._serialized_end=207
  _CREATEREPLY._serialized_start=209
  _CREATEREPLY._serialized_end=239
  _ACCESSREQUEST._serialized_start=241
  _ACCESSREQUEST._serialized_end=271
  _ACCESSREPLY._serialized_start=273
  _ACCESSREPLY._serialized_end=305
  _TERMINOREQUEST._serialized_start=307
  _TERMINOREQUEST._serialized_end=323
  _TERMINOREPLY._serialized_start=325
  _TERMINOREPLY._serialized_end=356
  _IDENTIDADES._serialized_start=359
  _IDENTIDADES._serialized_end=594
# @@protoc_insertion_point(module_scope)
